#!/usr/bin/env python3

# usage:
#   $ ./font.py < font-master.txt > wizfont.a
#   $ acme -o wizfont.bin wizfont.a

import fileinput
import itertools

height = 7
all_chars = list(map(chr, range(0x20, 0x60)))

data = {}
min_index = 0x20
mid_index = 0x40
max_index = 0x60
with fileinput.input(encoding="utf-8") as f:
    for c in all_chars:
        data[c] = {}
        data[c]["description"] = f.readline().strip()[1:]
        data[c]["rawbits"] = []
        for row in range(height):
            rawbits = f.readline().strip()
            data[c]["rawbits"].append(rawbits)

print("; Wizard Replay Mono pixel font")
print("; (c) 2025 by 4am")
print("; license:Open Font License 1.1, see OFL.txt")
print("; derived from Replay Mono, (c) 2025 by 4am")
print("; https://github.com/a2-4am/fonts/tree/main/Replay%20Mono")
print(";")
print("; - includes only uppercase letters and basic punctuation")
print(";   (ASCII $20-$5F) and replaces @ with a cursor shape")
print("; - has a vertical spacing line above each character")
print(";   instead of below, to match Wizardry's original font behavior")
print("; - is in a specific (non-ascending) order to facilitate patching")
print(";")
print("; This file is automatically generated")
print(";")
print("*=0")
print()

# output second half of ASCII range
# then first half
for c in map(chr, itertools.chain(range(mid_index, max_index),
                                  range(min_index, mid_index))):
    description = data[c]['description']
    rawbits = data[c]["rawbits"]
    print(f"         !byte %00000000 ; {description}")
    for row in range(height):
        print(f"         !byte %0{rawbits[row][::-1]} ; {description}")
